# Generated by Django 5.0.7 on 2024-07-15 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watermeterdata',
            old_name='reading_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='watermeterdata',
            old_name='reading_value',
            new_name='value',
        ),
        migrations.AlterUniqueTogether(
            name='watermeterdata',
            unique_together={('water_meter', 'date')},
        ),
    ]
