# Generated by Django 5.0.7 on 2024-07-16 15:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_rename_reading_date_watermeterdata_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermeterdata',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 7, 16, 15, 50, 21, 957292), help_text='укажите дату снятия показания', verbose_name='Дата показания:'),
        ),
        migrations.CreateModel(
            name='CalculationResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('rent', 'rent'), ('water_meter', 'water_meter')], max_length=255)),
                ('date', models.DateField(default=datetime.datetime(2024, 7, 16, 15, 50, 21, 957909))),
                ('result', models.PositiveIntegerField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_result', to='infrastructure.apartment')),
                ('water_meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calculation_result', to='infrastructure.watermeter')),
            ],
        ),
    ]
