# Generated by Django 5.0.7 on 2024-07-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_alter_calculationresults_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculationresults',
            name='water_meter',
        ),
    ]
