# Generated by Django 5.0.7 on 2024-07-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_remove_calculationresults_water_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(help_text='укажите название дома', max_length=255, verbose_name='Название:'),
        ),
    ]
